### ISSUE TITLE
language tag validation and dependency

### ISSUE THREAD

**Issue by mrhota** [pyfisch/rust-language-tags#5]
I have a work-in-progress [CLDR crate](https://crates.io/crates/cldr) which may be of use to this project. With CLDR data, you can perform validation and substitution/replacement of subtags. Do you have any interest in using the CLDR crate as an optional dependency for validation?

In addition, I want to use LanguageTags as keys for data lookup in CLDR data, but I don't know how to deal with circular dependencies (if `language-tags` uses `cldr` to perform validation, and `cldr` uses `language-tags` to lookup locale-specific data). Thoughts?

**Comment by pyfisch** [comment]
Having a CLDR crate for rust is a great idea! The Unicode CLDR is really comprehensive for this reason I do not want to include it in the language-tag crate. Some basic validation can be done without knowing all language codes and the tags can also be used to choose the best matching language of a given resource.  Deprecated subtags are already replaced.

Since `language-tags` will not depend on `cldr` you can just use them as keys for data lookup. Please note that I want to rewrite `language-tags` like the `url` crate to only use one allocation per tag and [store the position of various parts of the tag](https://github.com/servo/rust-url/blob/master/src/lib.rs#L160-L182).

**Comment by pyfisch** [comment]
CLDR crate was yanked.
